name: 'Test Env'
on: 
    - workflow_dispatch
    - push

jobs: 
    preproduction: 
        runs-on: ubuntu-latest
        environment:
            name: preproduction
        steps:
            - name: 'Deploy to preprod'
              run: |
                echo 'Deploying!!!!!!!'
            
    preview:
        runs-on: ubuntu-latest
        environment:
            name: preview
        steps:
            - name: 'Deploy to another env'
              run: |
                echo 'Deploying with rules!!!!!!!'